### ISSUE TITLE
ERROR - Dynamic model import failed

### ISSUE THREAD

**Issue by jkhchan307** [valhuber/ApiLogicServer#13]
Traceback (most recent call last):
  File "c:\users\xxxxxxx\source\vscode\als\venv\lib\site-packages\api_logic_server_cli\cli.py", line 248, in find_meta_data
    importlib.import_module('models')
  File "c:\users\xxxxxxx\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module     
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/database\models.py", line 3483, in <module>
    class EXPORTPARAM(SAFRSBase, Base):
  File "C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/database\models.py", line 3499, in EXPORTPARAM
    ROW_0_FLAG = Column(CHAR(1, 'Chinese_Taiwan_Stroke_BIN'))
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

![image](https://user-images.githubusercontent.com/20136568/114374145-e77c4900-9bb5-11eb-82f3-5351582be958.png)

**Comment by valhuber** [comment]
Thanks for reporting.  Can you supply database (eg, DDL), or some easy way to recreate?

**Comment by jkhchan307** [comment]
CREATE TABLE [dbo].[EXPORT_PARAM](
	[API_NAME] [nvarchar](50) NOT NULL,
	[ENV] [nvarchar](10) NOT NULL,
	[RNK] [int] NOT NULL,
	[CATEGORY] [nvarchar](20) NULL,
	[WHERE_CLAUSE] [nvarchar](300) NULL,
	[TEMP_PATH] [nvarchar](300) NULL,
	[TEMP_FILE] [nvarchar](100) NULL,
	[OUT_PATH] [nvarchar](300) NULL,
	[OUT_FILE_NAME] [nvarchar](100) NULL,
	[ZIP_FLAG] [nvarchar](1) NULL,
	[ZIP_FILE_NAME] [nvarchar](100) NULL,
	[ZIP_PATH_BEFORE] [nvarchar](300) NULL,
	[ZIP_PATH_AFTER] [nvarchar](300) NULL,
	[ROW_0_FLAG] [char](1) NULL,
 CONSTRAINT [PK_EXPORT_PARAM] PRIMARY KEY CLUSTERED 
(
	[API_NAME] ASC,
	[ENV] ASC,
	[RNK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

![image](https://user-images.githubusercontent.com/20136568/114394533-e48d5280-9bcd-11eb-9bd8-c35d8bbb27a0.png)

**Comment by valhuber** [comment]
Temp fix available: https://test.pypi.org/project/ApiLogicServer/2.0.7/

Please advise if this resolves your issue, and thanks again for the report.

**Comment by jkhchan307** [comment]
Seemed to be no change:

ApiLogicServer **02.00.07** Creation Log:
1. Delete dir: C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server
2. Create Project copy c:\users\xxxxxxx\source\vscode\als\venv\lib\site-packages\prototype -> api_logic_server
4. Create api_logic_server/database/models.py via expose_existing / sqlacodegen: mssql://XXX_XXXX
5. Create ui/basic_web_app with command: flask fab create-app --name C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/ui/basic_web_app --engine SQLAlchemy
5. Create ui/basic_web_app with command: flask fab create-app --name C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/ui/basic_web_app --engine SQLAlchemy result: Downloaded the skeleton app, good coding!\r
6. Create api/expose_api_models.py and ui/basic_web_app/app/views.py (import / iterate models)
.. ..Dynamic model import using sys.path: C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/database

===> ERROR - Dynamic model import failed
Traceback (most recent call last):
  File "c:\users\xxxxxxx\source\vscode\als\venv\lib\site-packages\api_logic_server_cli\cli.py", line 248, in find_meta_data
    importlib.import_module('models')
  File "c:\users\xxxxxxx\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/database\models.py", line 3483, in <module>
    class EXPORTPARAM(SAFRSBase, Base):
  File "C:\Users\xxxxxxx\source\vscode\ALS\api_logic_server/database\models.py", line 3499, in EXPORTPARAM
    ROW_0_FLAG = Column(CHAR(1, 'Chinese_Taiwan_Stroke_BIN'))
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

**Comment by valhuber** [comment]
Hmm, sorry.... that is most odd.  Wondering if it's a cache issue?

If you are familiar with how to look into venv, can you verify that the fix is there (left code window, below).  The fix should result in a model file as shown in the right code window (this from my simplified test of your example).

We may perhaps do better on a screen share - I am valjhuber@gmail.com

<img width="1846" alt="fix verify" src="https://user-images.githubusercontent.com/5579631/114488996-31b9f600-9bc7-11eb-90e2-6fe4c24767c7.png">

**Comment by valhuber** [comment]
ah, I see it.  My bad.  the 2nd arg is different for you... I will have a fix in abut 30 mins

**Comment by valhuber** [comment]
ok, another try: https://test.pypi.org/project/ApiLogicServer/2.0.8/

**Comment by jkhchan307** [comment]
I started from totally fresh: 

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\xxxxxxx\source\vscode\ALS2> virtualenv venv
created virtual environment CPython3.8.3.candidate.1-64 in 52847ms
  creator CPython3Windows(dest=C:\Users\xxxxxxx\source\vscode\ALS2\venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=C:\Users\xxxxxxx\AppData\Local\pypa\virtualenv\seed-app-data\v1.0.1)
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
PS C:\Users\xxxxxxx\source\vscode\ALS2> venv/scripts/activate
(venv) PS C:\Users\xxxxxxx\source\vscode\ALS2> pip install ApiLogicServer-2.0.8-py3-none-any.whl
Processing c:\users\xxxxxxx\source\vscode\als2\apilogicserver-2.0.8-py3-none-any.whl
Collecting Flask-AppBuilder==3.1.1
  Using cached Flask_AppBuilder-3.1.1-py3-none-any.whl (1.7 MB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\9d\e7\4f\165e81b2d381987aae3ed1f1f71ec200ce1fbf2e6ffb6532a1\flask_admin-1.5.7-py3-none-any.whl
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Flask-Cors==3.0.0
  Using cached Flask_Cors-3.0.0-py2.py3-none-any.whl (15 kB)
Collecting SQLAlchemy==1.3.20
  Using cached SQLAlchemy-1.3.20-cp38-cp38-win_amd64.whl (1.2 MB)
Collecting PyMySQL>=1.0.2
  Using cached PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Collecting inflect==5.0.2
  Using cached inflect-5.0.2-py3-none-any.whl (31 kB)
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cryptography>=3.3.1
  Using cached cryptography-3.4.7-cp36-abi3-win_amd64.whl (1.6 MB)
Collecting email-validator==1.1.1
  Using cached email_validator-1.1.1-py2.py3-none-any.whl (17 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\e2\1e\3b\50c4d0d200bfe25d2686016f72859a5bd97822815065478358\sqlalchemy_utils-0.36.8-py2.py3-none-any.whl
Collecting logicbankutils==0.6.0
  Using cached logicbankutils-0.6.0-py3-none-any.whl (4.8 kB)
Collecting PyJWT==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting LogicBank>=0.9.3
  Using cached logicbank-0.9.6-py3-none-any.whl (41 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\7c\48\2c\7a7f4455d4a50140e5beefa5edfd475151d4d1832bd69b46d9\safrs-2.11.2-py3-none-any.whl
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting python-dotenv==0.15.0
  Using cached python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting Flask-WTF<0.15.0,>=0.14.2
  Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting marshmallow-sqlalchemy<0.24.0,>=0.22.0
  Using cached marshmallow_sqlalchemy-0.23.1-py2.py3-none-any.whl (18 kB)
Collecting click<8,>=6.7
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Flask-Babel<2,>=1
  Using cached Flask_Babel-1.0.0-py3-none-any.whl (9.5 kB)
Collecting prison<1.0.0,>=0.1.3
  Using cached prison-0.1.3-py2.py3-none-any.whl (5.8 kB)
Collecting marshmallow<4,>=3
  Using cached marshmallow-3.11.1-py2.py3-none-any.whl (46 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\ec\8e\42\16110a8b4f17e4ef4bd0abd42969fc1fc38229348de9f071df\flask_login-0.4.1-py2.py3-none-any.whl
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\a1\b3\ee\1bb518a7bcea32f7ae913ca5db6e68324f5cc09f1e13b81e96\flask_openid-1.2.5-py3-none-any.whl
Collecting Flask-SQLAlchemy<3,>=2.4
  Using cached Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\00\60\4a\7fc484ed75cc2baea756f0a3d07aa2065d09688d940c6fac1e\flask_jwt_extended-3.25.1-py2.py3-none-any.whl
Collecting colorama<1,>=0.3.9
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting apispec[yaml]<4,>=3.3
  Using cached apispec-3.3.2-py2.py3-none-any.whl (27 kB)
Collecting marshmallow-enum<2,>=1.5.1
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting jsonschema<4,>=3.0.1
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting wtforms
  Using cached WTForms-2.3.3-py2.py3-none-any.whl (169 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp38-cp38-win_amd64.whl (179 kB)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.1.0-py3-none-any.whl (241 kB)
Collecting idna>=2.0.0
  Using cached idna-3.1-py3-none-any.whl (58 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\69\ce\07\2361a747d34780afa5fc2d45a1703df920f73905a7f009ce0b\flask_swagger_ui-3.36.0-py3-none-any.whl
Collecting PyYAML>=5.1
  Using cached PyYAML-5.4.1-cp38-cp38-win_amd64.whl (213 kB)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\61\18\12\2b9369e2793fad39846d1383a15c38bf7ccc9ee7e95b873236\flask_restful_swagger_2-0.35-py3-none-any.whl
Collecting Babel>=2.3
  Using cached Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
Collecting pytz
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting python3-openid>=2.0
  Using cached python3_openid-3.2.0-py3-none-any.whl (133 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: setuptools in c:\users\xxxxxxx\source\vscode\als2\venv\lib\site-packages (from jsonschema<4,>=3.0.1->Flask-AppBuilder==3.1.1->ApiLogicServer==2.0.8) (46.1.3)
Processing c:\users\xxxxxxx\appdata\local\pip\cache\wheels\3d\22\08\7042eb6309c650c7b53615d5df5cc61f1ea9680e7edd3a08d2\pyrsistent-0.17.3-cp38-cp38-win_amd64.whl
Collecting MarkupSafe
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting Flask-RESTful>=0.2.12
  Using cached Flask_RESTful-0.3.8-py2.py3-none-any.whl (25 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting aniso8601>=0.82
  Using cached aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
Installing collected packages: MarkupSafe, wtforms, itsdangerous, Jinja2, Werkzeug, click, Flask, Flask-WTF, six, python-dateutil, dnspython, idna, email-validator, SQLAlchemy, marshmallow, marshmallow-sqlalchemy, pytz, Babel, Flask-Babel, prison, Flask-Login, defusedxml, python3-openid, Flask-OpenID, Flask-SQLAlchemy, PyJWT, Flask-JWT-Extended, colorama, SQLAlchemy-Utils, PyYAML, apispec, marshmallow-enum, attrs, pyrsistent, jsonschema, Flask-AppBuilder, Flask-Admin, Flask-Cors, PyMySQL, inflect, pycparser, cffi, cryptography, logicbankutils, LogicBank, flask-swagger-ui, aniso8601, Flask-RESTful, flask-restful-swagger-2, safrs, python-dotenv, ApiLogicServer
Successfully installed ApiLogicServer-2.0.8 Babel-2.9.0 Flask-1.1.2 Flask-Admin-1.5.7 Flask-AppBuilder-3.1.1 Flask-Babel-1.0.0 Flask-Cors-3.0.0 Flask-JWT-Extended-3.25.1 Flask-Login-0.4.1 Flask-OpenID-1.2.5 Flask-RESTful-0.3.8 Flask-SQLAlchemy-2.5.1 Flask-WTF-0.14.3 Jinja2-2.11.3 LogicBank-0.9.6 MarkupSafe-1.1.1 PyJWT-1.7.1 PyMySQL-1.0.2 PyYAML-5.4.1 SQLAlchemy-1.3.20 SQLAlchemy-Utils-0.36.8 Werkzeug-1.0.1 aniso8601-9.0.1 apispec-3.3.2 attrs-20.3.0 cffi-1.14.5 click-7.1.2 colorama-0.4.4 cryptography-3.4.7 defusedxml-0.7.1 dnspython-2.1.0 email-validator-1.1.1 flask-restful-swagger-2-0.35 flask-swagger-ui-3.36.0 idna-3.1 inflect-5.0.2 itsdangerous-1.1.0 jsonschema-3.2.0 logicbankutils-0.6.0 marshmallow-3.11.1 marshmallow-enum-1.5.1 marshmallow-sqlalchemy-0.23.1 prison-0.1.3 pycparser-2.20 pyrsistent-0.17.3 python-dateutil-2.8.1 python-dotenv-0.15.0 python3-openid-3.2.0 pytz-2021.1 safrs-2.11.2 six-1.15.0 wtforms-2.3.3 
WARNING: You are using pip version 20.1; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\xxxxxxx\source\vscode\ALS2\venv\Scripts\python.exe -m pip install --upgrade pip' command.
(venv) PS C:\Users\xxxxxxx\source\vscode\ALS2>



ApiLogicServer 02.00.08 Creation Log:
1. Delete dir: C:\Users\xxxxxxx\source\vscode\ALS2\api_logic_server
2. Create Project copy c:\users\xxxxxxx\source\vscode\als2\venv\lib\site-packages\prototype -> api_logic_server
4. Create api_logic_server/database/models.py via expose_existing / sqlacodegen: mssql+pyodbc://XXX_XXXX
5. Create ui/basic_web_app with command: flask fab create-app --name C:\Users\xxxxxxx\source\vscode\ALS2\api_logic_server/ui/basic_web_app --engine SQLAlchemy
5. Create ui/basic_web_app with command: flask fab create-app --name C:\Users\xxxxxxx\source\vscode\ALS2\api_logic_server/ui/basic_web_app --engine SQLAlchemy result: Downloaded the skeleton app, good coding!\r
6. Create api/expose_api_models.py and ui/basic_web_app/app/views.py (import / iterate models) 
.. ..Dynamic model import using sys.path: C:\Users\xxxxxxx\source\vscode\ALS2\api_logic_server/database

===> ERROR - Dynamic model import failed
Traceback (most recent call last):
  File "c:\users\xxxxxxx\source\vscode\als2\venv\lib\site-packages\api_logic_server_cli\cli.py", line 248, in find_meta_data
    importlib.import_module('models')
  File "c:\users\xxxxxxx\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\xxxxxxx\source\vscode\ALS2\api_logic_server/database\models.py", line 3716, 
in <module>
    Column('Effective_Date', CHAR(10, 'Chinese_Taiwan_Stroke_BIN')),
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

**Comment by valhuber** [comment]
thanks for hanging in there on this.  As you see, it's not always `CHAR(1,` your example above has` CHAR(10)`.

Perhaps I can change these to UNICODE, which is what I usually see for sql/server:
```
class Category(SAFRSBase, Base):
    __tablename__ = 'Categories'

    CategoryID = Column(Integer, primary_key=True)
    CategoryName = Column(Unicode(15), nullable=False, index=True)
    Description = Column(NTEXT(1073741823))
    Picture = Column(IMAGE)
```

Can you tell me what CHAR is, vs. UNICODE?  Even if they are different, perhaps we just use this as a temp fix to get you going while we do more research...?

**Comment by valhuber** [comment]
(as we can see, it's not a cache problem)

**Comment by valhuber** [comment]
I have another fix:

pip install -i https://test.pypi.org/simple/ ApiLogicServer==2.0.9

From this database:
```
create table DataTypes
(
	[Key] nvarchar(10) not null
		constraint DataTypes_pk
			primary key nonclustered,
	char_type char(10),
	varchar_type varchar(10)
)
go

```

It generates:
```
class DataType(SAFRSBase, Base):
    __tablename__ = 'DataTypes'

    Key = Column(Unicode(10), primary_key=True)
    char_type = Column(String(10, 'SQL_Latin1_General_CP1_CI_AS'))
    varchar_type = Column(String(10, 'SQL_Latin1_General_CP1_CI_AS'))

```

**Comment by jkhchan307** [comment]
2.0.9 seemed to have got me past the error. But when starting to run the api server, large number of the following messages appeared.

[2021-04-13 14:01:24,658] DEBUG: 'bool' object is not iterable
[2021-04-13 14:01:24,767] DEBUG: 'bool' object is not iterable
[2021-04-13 14:01:24,768] DEBUG: Failed to get python type for column Contact_20210224.DealCustomer (NotImplementedError)
[2021-04-13 14:01:24,769] DEBUG: Failed to get python type for column Contact_20210224.CanDM (NotImplementedError)
[2021-04-13 14:01:24,770] DEBUG: Failed to get python type for column Contact_20210224.CanFax (NotImplementedError)
[2021-04-13 14:01:24,771] DEBUG: Failed to get python type for column Contact_20210224.CanEmail (NotImplementedError)
[2021-04-13 14:01:24,771] DEBUG: Failed to get python type for column Contact_20210224.CanSM (NotImplementedError)
[2021-04-13 14:01:24,772] DEBUG: Failed to get python type for column Contact_20210224.ActiveCheck (NotImplementedError)

Column('CanDM', **BIT**, nullable=False),

Seemed to be caused by the BIT data type. Should I created another issue to track this instead? BTW, any concern about the message about 'bool' object is not iterable?

To be clear, the Swagger UI could still be accessed.

**Comment by thomaxxl** [comment]
the "Failed to get python type" messages are shown when safrs can't create a sample value for the swagger, the swagger will show "null" instead I think.

I am not sure what's causing the 'bool' error, can you paste the corresponding model?

**Comment by jkhchan307** [comment]
t_Contact_20161013 = Table(
    'Contact_20161013', metadata,
    Column('ContactID', Unicode(15), nullable=False),
    Column('FirstName', Unicode(30), nullable=False),
    Column('LastName', Unicode(30), nullable=False),
    Column('SalutationID', Unicode(10)),
    Column('DisplayName', Unicode(120), nullable=False),
    Column('NickName', Unicode(60)),
    Column('DealCustomer', BIT, nullable=False),
    Column('Lang', Unicode(3), nullable=False),
    Column('CurrencyID', Unicode(3), nullable=False),
    Column('CountryID', Unicode(3), nullable=False),
    Column('AreaID', Unicode(10)),
    Column('PassportID', Unicode(15)),
    Column('GovernmentID', String(15, 'Chinese_Taiwan_Stroke_CI_AS')),
    Column('Gender', Unicode(1)),
    Column('BloodType', Unicode(2)),
    Column('Birthday', Unicode(10)),
    Column('BirthPlace', Unicode(60)),
    Column('HighestDegree', NTEXT(1073741823)),
    Column('Anniversary', Unicode(10)),
    Column('Marry', Integer),
    Column('Spouse', Unicode(60)),
    Column('Children', Unicode(60)),
    Column('AnnualIncome', Float(53)),
    Column('BankName', Unicode(60)),
    Column('AccountType', Unicode(20)),
    Column('BankAccount', Unicode(20)),
    Column('Party', Unicode(60)),
    Column('Religion', Unicode(60)),
    Column('Profession', NTEXT(1073741823)),
    Column('Hobby', NTEXT(1073741823)),
    Column('ICQ', Unicode(20)),
    Column('Photo', IMAGE),
    Column('PrivPhoneNumberCountry', Unicode(5)),
    Column('PrivPhoneNumberArea', Unicode(5)),
    Column('PrivPhoneNumber', Unicode(20)),
    Column('AddressFrom', Integer),
    Column('OrigID', Unicode(20)),
    Column('OrigName', Unicode(60)),
    Column('ZipCode', Unicode(6)),
    Column('Address', Unicode(255)),
    Column('PhoneNumberCountry', Unicode(5)),
    Column('PhoneNumberArea', Unicode(5)),
    Column('PhoneNumber', Unicode(20)),
    Column('PhoneExt', Unicode(10)),
    Column('FaxNumberCountry', Unicode(5)),
    Column('FaxNumberArea', Unicode(5)),
    Column('FaxNumber', Unicode(20)),
    Column('ZipCode2', Unicode(6)),
    Column('Address2', Unicode(255)),
    Column('PhoneNumberCountry2', Unicode(5)),
    Column('PhoneNumberArea2', Unicode(5)),
    Column('PhoneNumber2', Unicode(20)),
    Column('PhoneExt2', Unicode(10)),
    Column('FaxNumberCountry2', Unicode(5)),
    Column('FaxNumberArea2', Unicode(5)),
    Column('FaxNumber2', Unicode(20)),
    Column('HomeZipCode', Unicode(6)),
    Column('HomeAddress', Unicode(255)),
    Column('HomePhoneNumberCountry', Unicode(5)),
    Column('HomePhoneNumberArea', Unicode(5)),
    Column('HomePhoneNumber', Unicode(20)),
    Column('HomeFaxNumberCountry', Unicode(5)),
    Column('HomeFaxNumberArea', Unicode(5)),
    Column('HomeFaxNumber', Unicode(20)),
    Column('Email', Unicode(255)),
    Column('Email2', Unicode(255)),
    Column('Email3', Unicode(255)),
    Column('PersonalHomePage', Unicode(255)),
    Column('MobilePhoneCountryCode', Unicode(5)),
    Column('MobilePhoneAreaCode', Unicode(5)),
    Column('MobilePhone', Unicode(20)),
    Column('MobilePhoneCountryCode2', Unicode(5)),
    Column('MobilePhoneAreaCode2', Unicode(5)),
    Column('MobilePhone2', Unicode(20)),
    Column('JobTypeID', Unicode(10)),
    Column('DepartmentName', Unicode(60)),
    Column('JobTitle', Unicode(30)),
    Column('AssistantName', Unicode(60)),
    Column('CanDM', BIT, nullable=False),
    Column('LastDMDate', Unicode(20)),
    Column('LastDMListID', Unicode(12)),
    Column('DMZipCode', Unicode(6)),
    Column('DMAddress', Unicode(255)),
    Column('CanFax', BIT, nullable=False),
    Column('LastFaxDate', Unicode(20)),
    Column('LastFaxListID', Unicode(12)),
    Column('SendFaxNumberCountry', Unicode(5)),
    Column('SendFaxNumberArea', Unicode(5)),
    Column('SendFaxNumber', Unicode(20)),
    Column('CanEmail', BIT, nullable=False),
    Column('LastEmailDate', Unicode(20)),
    Column('LastEmailListID', Unicode(12)),
    Column('CanSM', BIT, nullable=False),
    Column('LastSMDate', Unicode(20)),
    Column('LastSMListID', Unicode(12)),
    Column('CycleCountID', Unicode(5)),
    Column('CurrentLeads', Integer, nullable=False),
    Column('ExtNotes', NTEXT(1073741823)),
    Column('EntryID', Unicode(200)),
    Column('AttachID', Unicode(36), nullable=False),
    Column('CreateDeptID', Unicode(10)),
    Column('CreatorID', Unicode(10)),
    Column('CreateDate', Unicode(20)),
    Column('ModifyDeptID', Unicode(10)),
    Column('ModifierID', Unicode(10)),
    Column('ModifyDate', Unicode(20)),
    Column('OwnerID', Unicode(10)),
    Column('OwnerDeptID', Unicode(10)),
    Column('PermissionID', Unicode(36)),
    Column('chkflag', BigInteger, nullable=False),
    Column('CustomerType', Unicode(1)),
    Column('ServiceEmplID', Unicode(10), nullable=False),
    Column('MSNCode', Unicode(40)),
    Column('NominatorID', Unicode(15)),
    Column('Contact1', Unicode(30)),
    Column('MobilePhoneCountryCode3', Unicode(5)),
    Column('MobilePhoneAreaCode3', Unicode(5)),
    Column('MobilePhone3', Unicode(20)),
    Column('Contact2', Unicode(30)),
    Column('PhoneNumberCountry3', Unicode(5)),
    Column('PhoneNumberArea3', Unicode(5)),
    Column('PhoneNumber3', Unicode(20)),
    Column('PhoneExt3', Unicode(10)),
    Column('PrivPhoneNumberCountry2', Unicode(5)),
    Column('PrivPhoneNumberArea2', Unicode(20)),
    Column('PrivPhoneNumber2', Unicode(10)),
    Column('MobilePhoneCountryCode4', Unicode(5)),
    Column('MobilePhoneAreaCode4', Unicode(20)),
    Column('MobilePhone4', Unicode(10)),
    Column('Email4', Unicode(100)),
    Column('CompanyContact', Unicode(30)),
    Column('ActiveCheck', BIT, nullable=False),
    Column('MergeContactID', Unicode(10)),
    Column('MergeEmplID', Unicode(10)),
    Column('MergeDate', Unicode(20)),
    Column('OutBoundID', Unicode(10)),
    Column('EC_ID', DECIMAL(10, 0)),
    Column('TA_ID', DECIMAL(10, 0)),
    Column('ContactRate', Unicode(1), nullable=False),
    Column('ServiceAO', Unicode(6), nullable=False),
    Column('ContactGradeCDM', Unicode(1), nullable=False),
    Column('Centra_managed', Unicode(1)),
    Column('ExtNotes2', Unicode(255)),
    Column('MKT_CD1', Unicode(1)),
    Column('MKT_CD2', Unicode(1)),
    Column('MKT_CD3', Unicode(1)),
    Column('MKT_CD4', Unicode(1)),
    Column('MKT_CD5', Unicode(1)),
    Column('MKT_CD6', Unicode(1)),
    Column('MKT_CD7', Unicode(1))
)

**Comment by thomaxxl** [comment]
If the column type can't be determined, the swagger type will default to "string" (which is iterable), however in the case of a BIT, it should default to "integer" (or "boolean").
I'll extend this mapping dictionary and make it configurable too (atm, it's hardcoded).

This shouldn't pose much problems in the swagger.
