### ISSUE TITLE
Do you know fastapi

### ISSUE THREAD

**Issue by sylvoslee** [valhuber/ApiLogicServer#28]
Compared to the Fastapi ecosystem, is there still an advantage?

**Comment by valhuber** [comment]
From a cursory glance, the main differentiators appear to be:

Degree of automation - Fastapi enables you to write code for each endpoint.  API Logic Server / SAFRS automatically create end points for every table, including filtering, pagination and related data access.

Client creation - API Logic Server creates a multi-page, multi-table admin application

Transaction Logic - API Logic Server enables you write rules that address 95% of your backend logic for multi-table derivations and constraints.  Logic is 40x more concise than code.  Logic is extensible with event / actions for logic like email and message integration.

**Comment by valhuber** [comment]
From phone

Thanks,
Val

510-703-5909
